### ISSUE TITLE
#1: Set up readme.md

### ISSUE THREAD

**Issue by KirosC** [csci3250-2019/project-team-b#1]
Please set up the file **`readme.md`** with the following contents, which will be displayed automatically when entering this repo.

You have to finish these:
1. Set up 3 headings: **Introduction**, **Code**, and **Contributors**
2. Under **Introduction**, write a *short* summary of things your team will do according to the tasks inside the `issues` folder
3. Ensure your `readme.md` article is well-formatted with Markdown
4. There is no step 4!

**Comment by KirosC** [comment]
@chuckjee What's the content of **Code**? Thanks.

**Comment by ali-ahad** [comment]
Is this task to be done individually or as a team?

**Comment by KirosC** [comment]
> Is this task to be done individually or as a team?

Check out [task.md](https://github.com/csci3250-2019/project-team-b/blob/master/tasks.md). Each of us should have at least one task to do.

**Comment by ali-ahad** [comment]
> > Is this task to be done individually or as a team?
> 
> Check out [task.md](https://github.com/csci3250-2019/project-team-b/blob/master/tasks.md). Each of us should have at least one task to do.

So is task1 already done than?

**Comment by bpr4110** [comment]
I think the introduction should be modified
Task1 said need short summary about each task

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ali-ahad** [comment]
> https://aka.ms/ghei36

**Comment by ali-ahad** [comment]
I modified the introduction in task1. Tried to push to a branch I created for myself but I am not able to create a new pull request. How should I do it? How should i push the code from it?

**Comment by bpr4110** [comment]
click **New pull request"
Select your branch

**Comment by bpr4110** [comment]
@KirosC  Plz complete the **Introduction**
other parts of this task is modified and finished

**Comment by KirosC** [comment]
Updated. Awaiting approve.

**Comment by bpr4110** [comment]
Finished.
