### ISSUE TITLE
#5: Promote your repo

### ISSUE THREAD

**Issue by bpr4110** [csci3250-2019/project-team-b#10]
Now that your team has finished most of the tasks, you have to promote it! Your tasks:

1. Look at your team's page here: `https://csci3250-2019.github.io/project-team-b`
2. Go to the public repo of **`csci3250-2019.github.io`** in the CSCI3250 organization
3. Edit the file to add a link of your team, and request for review from @chuckjee
And there you're done!

**Comment by coffee-hamster** [comment]
Hi everyone, i will handle this issue. I will wait until all of the other works done by you guys

**Comment by coffee-hamster** [comment]
Hope we can do a great job

**Comment by bpr4110** [comment]
Finished

**Comment by coffee-hamster** [comment]
Thank you for your work @bpr4110 , I have already checked that it is fine.

**Comment by bpr4110** [comment]
You don't have to assign me to this.
I have already handled issue 4.
And actually this part is finished by @Andynguyen1 .
But he is also assigned to another issue...
So no need to change the assigned members.

?? Outlook for Android<https://aka.ms/ghei36>

________________________________
