### ISSUE TITLE
#4: Write C code

### ISSUE THREAD

**Issue by bpr4110** [csci3250-2019/project-team-b#6]
Please start to remember what you have done for C class. Or learn it anew.

Your tasks:

1. In **`code.c`**, write a piece of very simple (yet correct) C code (e.g. Hello World, simple for loop, simple if...then...else, etc.)
2. In **`readme.md`**, include your code (either copy & paste or `include_relative`)
3. Read this article to see how to get the GitHub shield for Travis CI, and put it inside **`readme.md`** with your code: https://hackernoon.com/continuous-integration-using-travis-on-github-1f7f2314b6b7

(Note: Travis CI is already installed on this repo)

**Comment by bpr4110** [comment]
On process
Waiting @chuckjee to install Travis CI to this repo
Otherwise I can't check/debug

**Comment by chuckjee** [comment]
Hi it's done!

**Comment by bpr4110** [comment]
Thx

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bpr4110** [comment]
all finished

**Comment by Niabubu** [comment]
emm  It seems that the rest of us got nothing to do, so I'll add some c code to help about this issue

**Comment by bpr4110** [comment]
Ok

?? Outlook for Android<https://aka.ms/ghei36>

________________________________
