### ISSUE TITLE
#2: Include data into readme

### ISSUE THREAD

**Issue by bpr4110** [csci3250-2019/project-team-b#7]
You are going to update this website: `https://csci3250-2019.github.io/project-team-b`

Please read about **`include_relative`** on this page: https://jekyllrb.com/docs/includes/

Here are your tasks:

1. Edit **`readme.md`**
2. Under **Contributors**, use **`include_relative`** to include your own md file under the folder `_stu`
3. At the bottom of the page, include the last updated time using `site.time` (HOW?)
(Feel free to enhance the page outlook by changing the theme, or preparing new CSS!)

**Comment by bpr4110** [comment]
Waiting new members.
At this moment completed

**Comment by ali-ahad** [comment]
Is it possible to show the code on readme?
Also can anyone correct the readme so that it shows the link

**Comment by bpr4110** [comment]
I think there is no problem in readme?
U can see the actual effect on https://csci3250-2019.github.io/project-team-b/
Btw @a0030609 @wbxqmll your md file's content has some mistake
Check carefully and amend it.
