### ISSUE TITLE
#3: Project board

### ISSUE THREAD

**Issue by bpr4110** [csci3250-2019/project-team-b#9]
Please explore the **Projects** tab

Your tasks:

1. Create a new project board (with any name), and use the **Basic Kanban** template, containing "*To do*", "*In Progress*", and "*Done*"
2. Set up these automations:
* When pull requests are added, put the item in "In progress"
* When issues are closed, put the item in "Done"
* When pull requests are merged, put the item in "Done"
3. Regularly visit the **Issues** and **Pull requests** tabs to make sure all items are marked with your project board

**Comment by ali-ahad** [comment]
Completed

**Comment by coffee-hamster** [comment]
I am afraid that this issue have not completed yet because this is no assignee. Did ali-ahad do this issue? If so, then ali-ahad should assign himself.

**Comment by ali-ahad** [comment]
Assigned

**Comment by coffee-hamster** [comment]
Thank you for your work, I have double checked. It is fine.
